disabled_rules: # rule identifiers to exclude from running
- file_length
- function_body_length
- line_length
- statement_position
- todo
- valid_docs
- conditional_binding_cascade
#enabled_rules: # some rules are only opt-in
#  - empty_count
#  - missing_docs
#  # Find all the available rules by running:
#  # swiftlint rules
#included: # paths to include during linting. `--path` is ignored if present.
#  - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Tests
- Playgrounds
force_cast:
  severity: warning
force_try:
  severity: warning
variable_name:
  min_length: # only min_length
    warning: 4 # only error
  excluded: # excluded via string array
    - lhs
    - rhs
    - f
    - crc
    - url
    - hex
    - i
    - key
    - _value
    - _valueChanged
